export const complexOrdersArchieveGroup = {
  _id: "$_id",
  products: {
    $push: {
      product: "$productDetails",
      quantity: "$products.quantity",
      price: "$products.price",
    },
  },
  order_type: { $first: "$order_type" },
  payments: { $first: "$payments" },
  description: { $first: "$description" },
  user: { $first: "$user" },
  submitter: { $first: "$submitter" },
  complex_user: { $first: "$complex_user" },
  user_address: { $first: "$user_address" },
  user_phone: { $first: "$user_phone" },
  shipping_price: { $first: "$shipping_price" },
  packing_price: { $first: "$packing_price" },
  total_price: { $first: "$total_price" },
  extra_price: { $first: "$extra_price" },
  complex_discount: { $first: "$complex_discount" },
  user_discount: { $first: "$user_discount" },
  user_cashback: { $first: "$user_cashback" },
  table_number: { $first: "$table_number" },
  status: { $first: "$status" },
  factor_number: { $first: "$factor_number" },
  tax: { $first: "$tax" },
  tip: { $first: "$tip" },
  service: { $first: "$service" },
  created_at: { $first: "$created_at" },
  delivery_guy: { $first: "$delivery_guy" },
  delivery_time: { $first: "$delivery_time" },
  people_count: { $first: "$people_count" },
};
